#!/bin/bash

set -eou pipefail

# echo "The script you are running has basename $( basename -- "$0"; ), $(dirname -- "$( readlink -f -- "$0"; )";)"
# echo "The present working directory is $( pwd; )";


SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )";)
SCRIPT_NAME=iam-assume-role

ln -fs "${SCRIPT_DIR}"/"${SCRIPT_NAME}" "${HOME}"/.local/bin/"${SCRIPT_NAME}"

# Check if alias already exists..."
if ! grep assume-role "${HOME}"/.aliases.local &>/dev/null ; then
    echo 'alias assume-role="source iam-assume-role $@"' >> ~/.aliases.local
else
    echo "[-] Alias 'assume-role' already exists!"    
fi

echo "Finished!"
